/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cartoon_plane.glb 
Author: antonmoek (https://sketchfab.com/antonmoek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-plane-f312ec9f87794bdd83630a3bc694d8ea
Title: Cartoon Plane
*/
import { useFrame } from "@react-three/fiber";
import React, { useRef, useEffect, Suspense } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function PlaneModel(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/cartoon_plane.glb");
  const { actions } = useAnimations(animations, group);
  const propellerRef = useRef();

  
  useEffect(() => {
    if (materials && materials.material) {
      materials.material.color.set("#1E90FF");
    }
  }, [materials]);

  useFrame(() => {
    if (propellerRef.current) {
      propellerRef.current.rotation.z += 0.5;
    }
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.002}
        >
          <group
            name="12cc6a9ff2ae45b08826ba235d9cb8b7fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Propeller_1"
                  ref={propellerRef}
                  position={[0.873, -46.025, 401.434]}
                >
                  <mesh
                    name="Propeller_1_Red_0"
                    geometry={nodes.Propeller_1_Red_0.geometry}
                    material={materials.material}
                  />
                  <mesh
                    name="Propeller_1_Body_0"
                    geometry={nodes.Propeller_1_Body_0.geometry}
                    material={materials.Body}
                  />
                </group>
                <group name="Physical_Sky" rotation={[-0.053, -0.495, -0.003]}>
                  <group name="Sky_Null" position={[195.251, 64.455, 239.448]}>
                    <group
                      name="Sun"
                      position={[-8659.807, 52407.355, 138158.203]}
                      rotation={[-0.363, -0.059, -0.022]}
                    />
                    <group
                      name="Moon"
                      position={[-3951.259, 517.194, -640.605]}
                      rotation={[-2.462, -1.365, -2.473]}
                    />
                  </group>
                  <group name="Shadow_Plane" position={[0, 10000, 0]} />
                </group>
                <group name="Plane" position={[-2.544, -22.784, 0]}>
                  <group
                    name="Wheel_Back"
                    position={[3.215, -59.613, -256.318]}
                    rotation={[0.169, -0.004, -0.021]}
                  >
                    <group
                      name="Cylinder_1"
                      position={[6.518, -27.543, 0]}
                      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                    >
                      <mesh
                        name="Cylinder_1_Body_0"
                        geometry={nodes.Cylinder_1_Body_0.geometry}
                        material={materials.Body}
                      />
                    </group>
                    <group name="WheelCarcas" position={[114.386, 59.17, 0]}>
                      <mesh
                        name="WheelCarcas_Body_0"
                        geometry={nodes.WheelCarcas_Body_0.geometry}
                        material={materials.Body}
                      />
                    </group>
                    <group
                      name="Wheel"
                      position={[0.622, -32.49, 0]}
                      rotation={[0, 0, -Math.PI / 2]}
                    >
                      <mesh
                        name="Wheel_Gum_0"
                        geometry={nodes.Wheel_Gum_0.geometry}
                        material={materials.material_3}
                      />
                    </group>
                  </group>
                  <group
                    name="Wheel_1"
                    position={[81.31, -76.376, 232.741]}
                    rotation={[0, 0, 0.328]}
                  >
                    <group
                      name="Cylinder_1_2"
                      position={[12.173, -51.437, 0]}
                      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                    >
                      <mesh
                        name="Cylinder_1_2_Body_0"
                        geometry={nodes.Cylinder_1_2_Body_0.geometry}
                        material={materials.Body}
                      />
                    </group>
                    <group
                      name="WheelCarcas_2"
                      position={[213.613, 110.499, 0]}
                    >
                      <mesh
                        name="WheelCarcas_2_Body_0"
                        geometry={nodes.WheelCarcas_2_Body_0.geometry}
                        material={materials.Body}
                      />
                    </group>
                    <group
                      name="Wheel_2"
                      position={[1.162, -60.674, 0]}
                      rotation={[0, 0, -Math.PI / 2]}
                    >
                      <mesh
                        name="Wheel_2_Gum_0"
                        geometry={nodes.Wheel_2_Gum_0.geometry}
                        material={materials.material_3}
                      />
                    </group>
                  </group>
                  <group
                    name="Wheel_3"
                    position={[-81.572, -76.376, 232.741]}
                    rotation={[0, 0, -0.324]}
                  >
                    <group
                      name="Cylinder_1_3"
                      position={[12.173, -51.437, 0]}
                      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                    >
                      <mesh
                        name="Cylinder_1_3_Body_0"
                        geometry={nodes.Cylinder_1_3_Body_0.geometry}
                        material={materials.Body}
                      />
                    </group>
                    <group
                      name="WheelCarcas_3"
                      position={[213.613, 110.499, 0]}
                    >
                      <mesh
                        name="WheelCarcas_3_Body_0"
                        geometry={nodes.WheelCarcas_3_Body_0.geometry}
                        material={materials.Body}
                      />
                    </group>
                    <group
                      name="Wheel_4"
                      position={[1.162, -60.674, 0]}
                      rotation={[0, 0, -Math.PI / 2]}
                    >
                      <mesh
                        name="Wheel_4_Gum_0"
                        geometry={nodes.Wheel_4_Gum_0.geometry}
                        material={materials.material_3}
                      />
                    </group>
                  </group>
                  <group
                    name="Air_motor_right"
                    position={[0, -45.567, 0]}
                    rotation={[0, 0, -Math.PI]}
                  >
                    <group name="Cube_2">
                      <mesh
                        name="Cube_2_Body_0"
                        geometry={nodes.Cube_2_Body_0.geometry}
                        material={materials.Body}
                      />
                    </group>
                    <group name="Cube_1">
                      <mesh
                        name="Cube_1_Body_0"
                        geometry={nodes.Cube_1_Body_0.geometry}
                        material={materials.Body}
                      />
                    </group>
                    <group name="Cube">
                      <mesh
                        name="Cube_Body_0"
                        geometry={nodes.Cube_Body_0.geometry}
                        material={materials.Body}
                      />
                    </group>
                  </group>
                  <group name="Air_motor_left" position={[0, 22.784, 0]}>
                    <group name="Cube_2_2">
                      <mesh
                        name="Cube_2_2_Body_0"
                        geometry={nodes.Cube_2_2_Body_0.geometry}
                        material={materials.Body}
                      />
                    </group>
                    <group name="Cube_1_2">
                      <mesh
                        name="Cube_1_2_Body_0"
                        geometry={nodes.Cube_1_2_Body_0.geometry}
                        material={materials.Body}
                      />
                    </group>
                    <group name="Cube_2_3">
                      <mesh
                        name="Cube_2_3_Body_0"
                        geometry={nodes.Cube_2_3_Body_0.geometry}
                        material={materials.Body}
                      />
                    </group>
                  </group>
                  <group name="Body" position={[0, 22.784, 0]}>
                    <group name="Cube_1_3">
                      <mesh
                        name="Cube_1_3_Body_0"
                        geometry={nodes.Cube_1_3_Body_0.geometry}
                        material={materials.Body}
                      />
                      <mesh
                        name="Cube_1_3_Red_0"
                        geometry={nodes.Cube_1_3_Red_0.geometry}
                        material={materials.material}
                      />
                      <mesh
                        name="Cube_1_3_Glass_0"
                        geometry={nodes.Cube_1_3_Glass_0.geometry}
                        material={materials.Glass}
                      />
                      <mesh
                        name="Cube_1_3__0"
                        geometry={nodes.Cube_1_3__0.geometry}
                        material={materials.Cube_1_3__0}
                      />
                    </group>
                    <group name="Cube_3">
                      <mesh
                        name="Cube_3_Body_0"
                        geometry={nodes.Cube_3_Body_0.geometry}
                        material={materials.Body}
                      />
                      <mesh
                        name="Cube_3_Red_0"
                        geometry={nodes.Cube_3_Red_0.geometry}
                        material={materials.material}
                      />
                      <mesh
                        name="Cube_3_Glass_0"
                        geometry={nodes.Cube_3_Glass_0.geometry}
                        material={materials.Glass}
                      />
                      <mesh
                        name="Cube_3__0"
                        geometry={nodes.Cube_3__0.geometry}
                        material={materials.Cube_1_3__0}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/cartoon_plane.glb");
