"""Remove activity feature and related tables

Revision ID: 1cafa1837b7b
Revises: ddc97df2a1e9
Create Date: 2025-07-10 12:14:26.792464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cafa1837b7b'
down_revision: Union[str, Sequence[str], None] = 'ddc97df2a1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop package_activities first due to FK constraint, then activities
    op.drop_table('package_activities')
    op.drop_table('activities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_activities',
    sa.Column('package_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_included', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('package_activities_activity_id_fkey')),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('package_activities_package_id_fkey')),
    sa.PrimaryKeyConstraint('package_id', 'activity_id', name=op.f('package_activities_pkey'))
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_hours', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('featured_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('activities_pkey'))
    )
    # ### end Alembic commands ###
