"""update_models

Revision ID: 3b073b1f7182
Revises: 080833d71611
Create Date: 2025-07-08 23:03:46.057199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b073b1f7182'
down_revision: Union[str, Sequence[str], None] = '080833d71611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package_schedules', 'min_age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_schedules', sa.Column('min_age', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
