"""update  models

Revision ID: 4a979c68464c
Revises: 1de98b55c41c
Create Date: 2025-07-15 15:21:57.763877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a979c68464c'
down_revision: Union[str, Sequence[str], None] = '1de98b55c41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('package_detail_schedule_package_id_key'), 'package_detail_schedule', type_='unique')
    op.drop_column('package_detail_schedule', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_detail_schedule', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('package_detail_schedule_package_id_key'), 'package_detail_schedule', ['package_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
