"""Add standalone promo code fields

Revision ID: 4e18041aac0f
Revises: 2a1a2e39e4de
Create Date: 2025-06-30 16:36:11.963473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e18041aac0f'
down_revision: Union[str, Sequence[str], None] = '2a1a2e39e4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
