"""Add image fields to destinations and activities

Revision ID: 91cf0ec60480
Revises: dd2cdd8728eb
Create Date: 2025-06-29 21:21:27.258779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91cf0ec60480'
down_revision: Union[str, Sequence[str], None] = 'dd2cdd8728eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('featured_image', sa.TEXT(), nullable=True))
    op.add_column('activities', sa.Column('images', postgresql.ARRAY(sa.TEXT()), nullable=True))
    op.add_column('destinations', sa.Column('featured_image', sa.TEXT(), nullable=True))
    op.add_column('destinations', sa.Column('images', postgresql.ARRAY(sa.TEXT()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'images')
    op.drop_column('destinations', 'featured_image')
    op.drop_column('activities', 'images')
    op.drop_column('activities', 'featured_image')
    # ### end Alembic commands ###
