"""update_blog_author_from_admin_to_user

Revision ID: cc5f104502e7
Revises: 2ffe68ab7584
Create Date: 2025-07-03 23:11:19.879644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cc5f104502e7'
down_revision: Union[str, Sequence[str], None] = '2ffe68ab7584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blogs_author_id_fkey'), 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'users', ['author_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key(op.f('blogs_author_id_fkey'), 'blogs', 'admins', ['author_id'], ['id'])
    # ### end Alembic commands ###
