"""add_detailed_package_fields

Revision ID: d2a926d70725
Revises: c6d14125520f
Create Date: 2025-06-30 19:10:32.101173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2a926d70725'
down_revision: Union[str, Sequence[str], None] = 'c6d14125520f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('highlights', sa.TEXT(), nullable=True))
    op.add_column('packages', sa.Column('itinerary', sa.TEXT(), nullable=True))
    op.add_column('packages', sa.Column('inclusions', sa.TEXT(), nullable=True))
    op.add_column('packages', sa.Column('exclusions', sa.TEXT(), nullable=True))
    op.add_column('packages', sa.Column('terms_conditions', sa.TEXT(), nullable=True))
    op.add_column('packages', sa.Column('image_gallery', sa.TEXT(), nullable=True))
    op.add_column('packages', sa.Column('max_group_size', sa.INTEGER(), nullable=True))
    op.add_column('packages', sa.Column('min_age', sa.INTEGER(), nullable=True))
    op.add_column('packages', sa.Column('difficulty_level', sa.VARCHAR(length=50), nullable=True))
    op.add_column('packages', sa.Column('available_from', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('packages', sa.Column('available_until', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'available_until')
    op.drop_column('packages', 'available_from')
    op.drop_column('packages', 'difficulty_level')
    op.drop_column('packages', 'min_age')
    op.drop_column('packages', 'max_group_size')
    op.drop_column('packages', 'image_gallery')
    op.drop_column('packages', 'terms_conditions')
    op.drop_column('packages', 'exclusions')
    op.drop_column('packages', 'inclusions')
    op.drop_column('packages', 'itinerary')
    op.drop_column('packages', 'highlights')
    # ### end Alembic commands ###
