"""update admin models

Revision ID: e4ef4c31c2a4
Revises: 5384f986426d
Create Date: 2025-07-14 00:20:48.333277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4ef4c31c2a4'
down_revision: Union[str, Sequence[str], None] = '5384f986426d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'permissions')
    op.drop_column('admins', 'is_super_admin')
    op.drop_column('admins', 'last_login_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('admins', sa.Column('is_super_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('admins', sa.Column('permissions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
