"""update  models

Revision ID: f8b7e10a9c92
Revises: 4a979c68464c
Create Date: 2025-07-15 22:24:52.024118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8b7e10a9c92'
down_revision: Union[str, Sequence[str], None] = '4a979c68464c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add as nullable
    op.add_column('destinations', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_unique_constraint('unique_destination_name_location', 'destinations', ['name', 'city', 'country'])
    op.create_foreign_key(None, 'destinations', 'admins', ['created_by'], ['id'])
    op.drop_column('destinations', 'timezone')
    # 2. Add as nullable
    op.add_column('packages', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_unique_constraint('unique_title_per_destination', 'packages', ['title', 'destination_id'])
    op.create_foreign_key(None, 'packages', 'admins', ['created_by'], ['id'])
    op.add_column('promo_codes', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'promo_codes', 'admins', ['created_by'], ['id'])
    # 3. Fill with a valid admin UUID (replace '00000000-0000-0000-0000-000000000001' with a real admin id)
    op.execute("UPDATE destinations SET created_by = '123e4567-e89b-12d3-a456-426614174000'")
    op.execute("UPDATE packages SET created_by = '123e4567-e89b-12d3-a456-426614174000'")
    op.execute("UPDATE promo_codes SET created_by = '123e4567-e89b-12d3-a456-426614174000'")
    # 4. Alter to NOT NULL
    op.alter_column('destinations', 'created_by', nullable=False)
    op.alter_column('packages', 'created_by', nullable=False)
    op.alter_column('promo_codes', 'created_by', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promo_codes', type_='foreignkey')
    op.drop_column('promo_codes', 'created_by')
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.drop_constraint('unique_title_per_destination', 'packages', type_='unique')
    op.drop_column('packages', 'created_by')
    op.add_column('destinations', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'destinations', type_='foreignkey')
    op.drop_constraint('unique_destination_name_location', 'destinations', type_='unique')
    op.drop_column('destinations', 'created_by')
    # ### end Alembic commands ###
